### ISSUE TITLE
Order of operations to get a pull request for a file

### ISSUE THREAD

**Issue by lcardani** [githubschool/funny-lemur#152]
@beardofedu 
I am going over my notes and I am confused.  I have a new branch cardani_branch2, with a new file cardani-shrewsbury.md.  I change the file, do a git add of the file then a git commit of the file.

How do I get a pull request, so I can collaborate then merge in my file?  When I try to do a New Pull Request, with Master compared to my cardani_branch2, it says There isn't anything to compare.

What am I doing wrong?

**Comment by lcardani** [comment]
Do I need an issue first somehow>

**Comment by lcardani** [comment]
@crichID What am I doing wrong?

**Comment by crichID** [comment]
@lcardani did you do a `git push` from your local repository up to GitHub?

**Comment by lcardani** [comment]
1.  I do a git status:
C:\github\scrap\funny-lemur>git status
On branch cardani_branch2
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   cardani-shrewsbury.md

2. I do a git push and get an error:
C:\github\scrap\funny-lemur>git push cardani-shrewsbury.md
fatal: Invalid gitfile format: cardani-shrewsbury.md
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by lcardani** [comment]
(I had cleaned up my folders and tried to start from scratch).

**Comment by beardofedu** [comment]
@lcardani So your file is currently modified and in the "Working Directory" we need to move it from the "Working Directory" to the "Staging Area" with `git add`. So:

1. Enter, `git add cardani-shrewsbury.md`
1. Enter, `git status` ; you should know see your file ready to be committed
1. Enter, `git commit -m "your commit message"
1. Enter, `git push` ; you don't actually push specific files, you push the current status of your branch (which is the latest commit) to your remote repository

Let us know if you run into any issues pushing your file after following those steps.

**Comment by lcardani** [comment]
OK, I tried to follow your steps:
1. Modified file.
2. Git status:
C:\github\scrap\funny-lemur>git status
On branch cardani_branch2
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   cardani-shrewsbury.md

no changes added to commit (use "git add" and/or "git commit -a")
3. git add cardani-shrewsbury.md
4. git status
C:\github\scrap\funny-lemur>git status
On branch cardani_branch2
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   cardani-shrewsbury.md
5. Commit:
C:\github\scrap\funny-lemur>git commit -m "my latest change for Shrewsbury MA"
[cardani_branch2 dff74aa] my latest change for Shrewsbury MA
 1 file changed, 1 insertion(+), 1 deletion(-)

6. git status
C:\github\scrap\funny-lemur>git status
On branch cardani_branch2
nothing to commit, working tree clean

7. git push:
C:\github\scrap\funny-lemur>git push
fatal: The current branch cardani_branch2 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin cardani_branch2

**Comment by beardofedu** [comment]
@lcardani Awesome! Now you just need to set the upstream for your branch:

`git push -u origin cardani_branch2`

After you push that, you will need to create a new Pull Request with:

`base: master` and `compare: cardani_branch2`

**Comment by lcardani** [comment]
Thanks, that push worked.  I don't remember doing that command before.  Could there have been a different way that we did it during class?  Or did I not get a chance to write that command down?

**Comment by beardofedu** [comment]
@lcardani Because you made the branch locally, Git needs you to tell it where you want to `push` it to. As a side note, something that helped me out a lot when I was learning Git, was how it provides a lot of great information, if you know what to look for.

For instance if we look at some of the terminal code you posted:

```
Changes not staged for commit:
(use "git add ..." to update what will be committed)
(use "git checkout -- ..." to discard changes in working directory)

 modified:   cardani-shrewsbury.md
```
In this instance, Git identifies that you modified the `cardani` file, and to use `git add` to update what will be committed. Obviously, it helps if you already understand what `committing` is and what `git add` does. 😄  

Another example:

```
git push:
C:\github\scrap\funny-lemur>git push
fatal: The current branch cardani_branch2 has no upstream branch.
To push the current branch and set the remote as upstream, use

git push --set-upstream origin cardani_branch2
```
In this example, "To push the current branch and set the remote as upstream, use
git push --set-upstream origin cardani_branch2"

Git identifies that you don't have a remote identified for this branch on your local machine (remote in this example, being the repository on GitHub). So it tells you to run a command to `set the remote`, however, without knowing what exactly a `remote` is, this message doesn't do much for you as the user.

I hope some of these examples help identify how you can potentially troubleshoot issues in the future as you continue on your adventures in Git and GitHub. If you encounter more issues or have other questions, _please_ feel free to ask. 

I'm super excited that you finished your Pull Request after class and look forward to class tomorrow!

![jawsome](https://media.giphy.com/media/YmiL1QKb89fPi/giphy.gif)

**Comment by lcardani** [comment]
Thanks!  My pull request / merge worked fine!

@beardofedu @crichID Thanks for the help!
