### ISSUE TITLE
@crich @githubteacher 

### ISSUE THREAD

**Issue by dunbam01** [githubschool/funny-lemur#160]
Why did my push go to github teacher?  And how do I fix that?

**Comment by crichID** [comment]
@dunbam01 it is probably because you cloned from githubteacher's copy of the repository instead of your own. Did you create the fork? If so, you should be able to use the following commands to fix it:

- `git remote set-url origin https://github.com/dunbam01/github-games.git`
- `git push -u origin readme-updates`
