### ISSUE TITLE
Merge Request

### ISSUE THREAD

**Issue by mohitgarg** [githubschool/funny-lemur#161]
What's the difference between squash and merge, rebase and merge and create a merge commit in the merge pull request drop down? @crichID

**Comment by crichID** [comment]
@mohitgarg great question! The biggest difference is how your history looks after the merge.

- **Create a merge commit** creates a new commit that represents the point in time when the two branches came together. These commits are special because they have 2 parents. When you look at your history with `git log --oneline --graph` and have a merge commit, you will always see where the branch was.
- **Squash and merge** takes all of the commits on the branch you are merging and makes them a single commit on master. In this case, you will only see a single commit that represents all of the changes on your branch. This makes a clean history, but you lose the granularity of your history.
- **Rebase and merge** takes all of the commits on the branch you are merging and replays them on top of the master branch. This allows the commits to be on master without creating the merge commit. In this case, when you look at your history, it looks like a straight line instead of showing where the branches once existed.

We will learn more about rebase later in class!
