### ISSUE TITLE
Can you explain to the class why just git push (without -u origin)?

### ISSUE THREAD

**Issue by lcardani** [githubschool/funny-lemur#163]
@crichID @beardofedu

**Comment by crichID** [comment]
@lcardani you only need to use `git push -u origin branch-name` when you create the branch locally. This is because you need to create the branch on the remote and set a relationship between the local branch and the one on GitHub (this is the role played by those red, remote tracking branches we were looking at yesterday).

Once this relationship is set, you only need to use `git push` because git already knows where to push.
