### ISSUE TITLE
Amend older commit messages

### ISSUE THREAD

**Issue by nmessier86** [githubschool/funny-lemur#166]
@beardofedu is there anyway to use the git commit --amend command on an older commit?  For example I made a typo in my README.md commit, what is the syntax to go back and amend that commit message?

**Comment by crichID** [comment]
@nmessier86 to amend a commit that is older than your most recent commit, you will need to use a different command. This is because changing that commit will change the parent of the commit after it -- therefore, all of the commits between the two points (the commit you are re-writing and now) will need to be rewritten. You can use rebase -i to do this, but be careful to only do this on commits that have not been pushed to the remote.
